# -*- coding: utf-8 -*-
"""Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zhZnFDa8TK-1ODDzAotSUWRR7WGPj466
"""

pip install google-genai

# --- Colab Setup and Authentication ---

# Install the necessary library
!pip install google-genai

# Import the Colab utility to safely load the API Key
from google.colab import userdata
from google import genai

# This will securely load the key you set in the Secrets Manager
try:
    GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')
    if not GEMINI_API_KEY:
        raise ValueError("API Key not found in Colab secrets.")

    # Initialize the client using the securely loaded key
    client = genai.Client(api_key=GEMINI_API_KEY)
    print("✅ Gemini Client initialized successfully using Colab Secrets.")

except Exception as e:
    print(f"❌ Error during client initialization: {e}")
    print("Please ensure you have set a secret named 'GEMINI_API_KEY' in the Colab Secrets Manager.")
    client = None # Set client to None if initialization fails

# --- Agent Logic (The Meal Planner) ---
from google.genai.errors import APIError

def get_meal_suggestion(ingredient: str, restriction: str):
    """
    The core logic of the Mobile Meal Planner Agent.
    """
    # Check if the client was successfully initialized in the previous cell
    if client is None:
        return "Error: Cannot run agent. Gemini client was not initialized."

    # This is the "prompt" - the instructions for your AI agent
    agent_instruction = (
        "You are a helpful and creative Mobile Meal Planner Agent. "
        "Your task is to generate a simple, easy-to-follow recipe for a beginner. "
        "Do not use complex or rare ingredients. The total time to prepare should be under 30 minutes. "
        "The response must be in the following format:\n\n"
        "## 🍽️ [Recipe Name]\n\n"
        "**Time:** [Total Time]\n\n"
        "**Ingredients:**\n* [Ingredient 1]\n* [Ingredient 2]\n* ...\n\n"
        "**Instructions:**\n1. [Step 1]\n2. [Step 2]\n3. ..."
    )

    # The actual user's request
    user_request = (
        f"Generate a recipe using the main ingredient: **{ingredient}**. "
        f"The recipe must strictly follow the dietary requirement: **{restriction}**."
    )

    full_prompt = agent_instruction + "\n\n" + user_request

    print("--- Sending Request to Agent ---")
    print(f"Ingredient: {ingredient}, Restriction: {restriction}")

    try:
        # Call the model
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=full_prompt
        )

        return response.text

    except APIError as e:
        return f"An API error occurred: {e}"
    except Exception as e:
        return f"An unexpected error occurred: {e}"

# --- Mobile Simulation: Run Test Cases with Client Check ---

if __name__ == "__main__":

    # Crucial check: only run the agent if the client was successfully initialized
    if client is None:
        print("\n❌ Cannot execute agent: Gemini client is not available. Please check the first Colab cell.")
        exit()

    # Example 1: Successful Query
    ingredient_input = "chicken"
    restriction_input = "low-carb"

    print("\nStarting Query 1...")
    recipe = get_meal_suggestion(ingredient_input, restriction_input)

    print("\n" + "="*50)
    print("✨ AGENT RESPONSE (Mobile Screen Output) ✨")
    print("="*50)
    print(recipe)
    print("="*50 + "\n")

    # Example 2: Different Query
    ingredient_input_2 = "cabbage"
    restriction_input_2 = "vegan"

    print("\nStarting Query 2...")
    recipe_2 = get_meal_suggestion(ingredient_input_2, restriction_input_2)

    print("\n" + "="*50)
    print("✨ AGENT RESPONSE (Second Query) ✨")
    print("="*50)
    print(recipe_2)
    print("="*50 + "\n")

